### ISSUE TITLE
Calling flush() too often results in a CallbackOverflowError

### ISSUE THREAD

**Issue by tsuna** [OpenTSDB/asynchbase#100]
In an app that uses batching but also aggressively flushes stuff to HBase, a high request rate plus aggressive calls to `flush()` lead to this:

```
com.stumbleupon.async.CallbackOverflowError: Too many callbacks in Deferred@1750061096(state=PENDING, result=null, callback=multi-action response -> notify Def
erredGroup@1340811160 -> notify DeferredGroup@1467258149 -> [...]
at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:669)
at com.stumbleupon.async.Deferred.addBoth(Deferred.java:772)
at com.stumbleupon.async.DeferredGroup.<init>(DeferredGroup.java:119)
at com.stumbleupon.async.Deferred.group(Deferred.java:897)
at org.hbase.async.RegionClient.sync(RegionClient.java:348)
at org.hbase.async.HBaseClient.flush(HBaseClient.java:609)
```

**Comment by asdf2014** [comment]
@tsuna I meet the same issues, any suggestion?

**Comment by binshi-bing** [comment]
@tsuna @asdf2014 @manolama, I entered the same issue -- any insight and suggestion?

**Comment by binshi-bing** [comment]
I just noticed that CallbackOverflowError was reported to OpenTSDB/asynchbase Community twice on 0214/11/28 and 2019/04/12 which never get response, and the issue is still keep open. I’m making choice between two approaches — fix AsyncHBase to avoid adding unnecessary callbacks to pending write RPCs due to NSRE; or reduce the number of flush() calls by increasing flush() granualarity in zen/ums and by avoiding aggressive retries/probing on NSRE.
