### ISSUE TITLE
nextRows eventually gives Assertion Error.

### ISSUE THREAD

**Issue by mohnishkodnani** [OpenTSDB/asynchbase#112]
Hi, 
I am trying to do a timerange scan using the following code. 

``` javascript
        val scanner = hbaseClient.newScanner(tableName)
        minTimeStamp.map(scanner.setMinTimestamp(_))
        maxTimeStamp.map(scanner.setMaxTimestamp(_))
        scanner.setFamily(columnFamily)
        //    scanner.setMaxVersions(1)
        @tailrec
        def scanHelper(scanner: Scanner, acc: ListBuffer[Future[ArrayList[ArrayList[KeyValue]]]]): ListBuffer[Future[ArrayList[ArrayList[KeyValue]]]] = {
            val result = Option(scanner.nextRows(1))
            result match {
                case Some(x) =>
                    log.info(s"Size of the scanned documents : ${acc.size}")
                    scanHelper(scanner, acc += x)
                case None =>
                    log.info(s"Done with scanner : ${acc.size}")
                    Try { scanner.close() }
                    acc
            }
        }

        val responses = scanHelper(scanner, ListBuffer.empty)
```

I get the counts increasing till about 1600 or so and then I get the following Stack trace.

``` javascript
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1683
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1684
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1684
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1685
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1685
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1686
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1686
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1687
2015-06-10 10:07:04,556 INFO [] [] - Size of the scanned documents : 1687
java.lang.AssertionError: Should never happen!  rpc=GetNextRowsRequest(scanner_id=0x00ADC4A816014C6E, max_num_rows=1, region=null, attempt=0)
        at org.hbase.async.RegionClient.encode(RegionClient.java:1134) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.RegionClient.sendRpc(RegionClient.java:894) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.HBaseClient.scanNextRows(HBaseClient.java:1110) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.Scanner.nextRows(Scanner.java:734) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.Scanner.nextRows(Scanner.java:672) ~[asynchbase-1.6.0.jar:na]
```

I enabled debug logging and it seems that one of the regions always fails with UnknownScannerException and it keeps retrying. 
If i run the same time range scan on the command line.
scan 'XYZ', { COLUMNS => ['B'], TIMERANGE => [1433955964165,1433956024158] }
I only get 22 results, but using the program nextRows(1) never returns null.
If I try nextRows() without any parameters it goes into an infinite loop.
How do I circumvent this issue. Anything incorrect on how I am using the library.

**Comment by mohnishkodnani** [comment]
Also, seeing this stack on occasion but eventually always getting the above mentioned AssertionError.
Below is the region that always fails.
```javascript
2015-06-10 10:56:45,432 ERROR[] [] - Uncaught exception while serializing RPC: OpenScannerRequest(scanner=Scanner(table="XYZ", start_key=[0, 18, 52, 86, 120, -102, -68, -33], stop_key="", columns={"B"}, populate_blockcache=true, max_num_rows=1, max_num_kvs=4096, region=null, filter=null, scanner_id=0x0EAD000AA000DEAD))
java.lang.ArrayIndexOutOfBoundsException: 149
        at org.jboss.netty.buffer.BigEndianHeapChannelBuffer.setInt(BigEndianHeapChannelBuffer.java:100) ~[netty-3.6.6.Final.jar:na]
        at org.jboss.netty.buffer.AbstractChannelBuffer.writeInt(AbstractChannelBuffer.java:422) ~[netty-3.6.6.Final.jar:na]
        at org.hbase.async.Scanner$OpenScannerRequest.serializeOld(Scanner.java:1334) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.Scanner$OpenScannerRequest.serialize(Scanner.java:1229) ~[asynchbase-1.6.0.jar:na]
        at org.hbase.async.RegionClient.encode(RegionClient.java:1146) [asynchbase-1.6.0.jar:na]
        at org.hbase.async.RegionClient.sendRpc(RegionClient.java:894) [asynchbase-1.6.0.jar:na]
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1698) [asynchbase-1.6.0.jar:na]
```

**Comment by AmitRGoswami** [comment]
Is any one got solution for this , i am getting same error 
Exception in thread "SinkRunner-PollingRunner-DefaultSinkProcessor" java.lang.AssertionError: Should never happen!  ..
        at org.hbase.async.RegionClient.encode(RegionClient.java:1134)
        at org.hbase.async.RegionClient.sendRpc(RegionClient.java:894)
        at org.hbase.async.HBaseClient.sendRpcToRegion(HBaseClient.java:1698)
        at org.hbase.async.HBaseClient.put(HBaseClient.java:1343)
        at org.apache.flume.sink.hbase.AsyncHBaseSink.process(AsyncHBaseSink.java:233)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mohnishkodnani** [comment]
Not yet. I used hbase client and don't see this error.

-----Original Message-----

**Comment by manolama** [comment]
@mohnishkodnani Sounds like I need to learn Scala:

What does your ``Option()`` method do? Does it wait for the results to be given from the deferred? Also, in that definition line, ``ListBuffer[Future[ArrayList[ArrayList[KeyValue]]]]`` looks suspicious. I'm thinking it should be ``ListBuffer[Deferred[ArrayList[ArrayList[KeyValue]]]]`` since AsyncHBase uses Deferred instead of Futures.

One thing you could try is to not pass in an integer to ``nextRows(1)``; it could be that a bug is lurking in there. Instead setup the scanner with a 1 row limit via ``scanner.setMaxNumRows(1);`` then call ``nextRows()``. 

The second error you're seeing is a bad sign as it means something may be goofy with the protocol. Which version of HBase are you using?

**Comment by manolama** [comment]
@AmitRGoswami In your case, what does your code look like with the PutRequest? That could happen if the request is re-used or if the callback was executed somewhere other than by AsyncHBase.

**Comment by IDerr** [comment]
@manolama You can close this one
