### ISSUE TITLE
Cannot set batch on a scan using a filter that returns true for filter.hasFilterRow

### ISSUE THREAD

**Issue by AMRivkin** [OpenTSDB/asynchbase#113]
How to set batch to 0?
asynchbase version 1.6.0, I have two filters ( BinaryComparator && RegexStringComparator)
Here is some additional info: 

Exception in thread "main" org.hbase.async.RemoteException: java.io.IOException: Cannot set batch on a scan using a filter that returns true for filter.hasFilterRow
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2070)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:108)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:116)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:96)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.hbase.filter.IncompatibleFilterException: Cannot set batch on a scan using a filter that returns true for filter.hasFilterRow
	at org.apache.hadoop.hbase.client.Scan.setBatch(Scan.java:379)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toScan(ProtobufUtil.java:954)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.scan(HRegionServer.java:3164)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:29925)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
	... 4 more

	at org.hbase.async.RegionClient.makeException(RegionClient.java:1450)
	at org.hbase.async.RegionClient.decodeException(RegionClient.java:1468)
	at org.hbase.async.RegionClient.decode(RegionClient.java:1299)
	at org.hbase.async.RegionClient.decode(RegionClient.java:89)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1082)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:555)
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:2677)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AMRivkin** [comment]
Need to set  scanner.setMaxNumKeyValues(-1);
