### ISSUE TITLE
asynchbase can work on a pseudo-distributed but failed on full cluster

### ISSUE THREAD

**Issue by evenX86** [OpenTSDB/asynchbase#126]
I can't connect the cluster with exception:

```
15:38:07,026  WARN ClientCnxn:1102 - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: 
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
```
But it can work on pseudo-distributed cluster.

**Comment by evenX86** [comment]
I'm sorry this issue,because I connect with the HMaster Node,When I read the HBaseClient, it should be zk node , its ok.
