### ISSUE TITLE
Hbase unable to insert the Record 

### ISSUE THREAD

**Issue by pavanshetty05** [OpenTSDB/asynchbase#127]
We are facing an issue in inserting the data in the Hbase . OpenTSDB is up and running we are getting the data from the TCollector . When we are inserting the data in the Hbase  it is taking more time to insert the data in it . Please find the below  warning message from the Hbase logs .
EndOfStreamException: Unable to read additional data from client sessionid 0x152c503a0dc0009, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
	at java.lang.Thread.run(Thread.java:745)
2016-02-09 09:21:33,118 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:58641 which had sessionid 0x152c503a0dc0009
Hbase version :- 1.1.3  version
OpenTSDB version :- 2.1.1 version

**Comment by pavanshetty05** [comment]
Some time it is taking half an our to insert the record in the Hbase .

**Comment by manolama** [comment]
The zookeeper connection probably timed out. See if the TSD is in GC for a long time as it can happen that asynchbase backs up a lot of RPCs in the NSRE or inflight queues and the client starts to run into long full GC pauses or just OOMs.
