### ISSUE TITLE
RPC waiting: PleaseThrottleException

### ISSUE THREAD

**Issue by nragon** [OpenTSDB/asynchbase#162]
Hi,

I'm using asynchbase with flink and a cloudera cluster. This erros keeps happening after 1.5million records processed. I've seen this before in other post, any tips on how to fix it?

Thank you,
Nuno

```
Caused by: org.hbase.async.PleaseThrottleException: 10000 RPCs waiting on "PGW_OUT_AGG,,1494943408113.7601eb7fa0725950d2060c0c0ee9c14a." to come back online
	at org.hbase.async.HBaseClient.handleNSRE(HBaseClient.java:2816)
	at org.hbase.async.RegionClient.failOrRetryRpcs(RegionClient.java:1212)
	at org.hbase.async.RegionClient.cleanup(RegionClient.java:1187)
	at org.hbase.async.RegionClient.channelClosed(RegionClient.java:1162)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)
	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.channelClosed(SimpleChannelHandler.java:216)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:106)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.timeout.IdleStateHandler.channelClosed(IdleStateHandler.java:286)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121)
	at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)
	at org.jboss.netty.channel.Channels$6.run(Channels.java:457)
	at org.jboss.netty.channel.socket.ChannelRunnableWrapper.run(ChannelRunnableWrapper.java:40)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by jake-maloney** [comment]
There is a property called hbase.region_client.inflight_limit that can be used to adjust the number of RPC's inflight before this is thrown (0 being disabled, but disabling means you can run out of memory) see [docs](http://opentsdb.github.io/asynchbase/docs/build/html/configuration.html). This is the only back-pressure mechanism in this hbase client that I am aware of. Since you are using flink which has its own back-pressure you might just want to wrap the client.put(PutRequest) in your own inflight counter that just sleeps and retries if it hits the limit, that way the pressure is pushed upstream as well.

**Comment by nragon** [comment]
@jake-maloney thanks, will probably add a semaphore with that limit. Seems that hbase.nsre.high_watermark is set with 10000, is it realted with "10000 RPCs waiting on"?

**Comment by nielsbasjes** [comment]
Sounds like you need to use a BufferedMutator.
In the old (0.9x) API HBase did buffering by default. 
In the new 1.x API they no longer do buffering and you should include a BufferedMutator yourself to avoid sending every Put/Delete individually.

**Comment by nragon** [comment]
@nielsbasjes I think HBaseClient does that. Each PutRequest Can have multiple qualifiers which internally will result in put.addColumn(....), so each row will only be sent once. No sure if that's what your'e trying to say. Thanks

**Comment by nielsbasjes** [comment]
In the old api the client did that. In the new api it doesn't.

**Comment by nragon** [comment]
My comment was based on this
https://github.com/OpenTSDB/asyncbigtable/blob/master/src/main/java/org/hbase/async/HBaseClient.java
I believe put method has a mutator. Can you confirm?

**Comment by nragon** [comment]
Does BatchableRpc do the job, simulating BufferedMutator?

**Comment by jake-maloney** [comment]
There is already buffering of normal PutRequests (it buffers all rpcs I believe) you can increase the size of the buffer via hbase.rpcs.batch.size (default is 1024 rpcs).

**Comment by nragon** [comment]
Yes, which in this case should simulate BufferedMutator. Although it's a good solution to add some semaphore to control throttle exceptions.

**Comment by nragon** [comment]
It seems another table, other than the first I've mentioned is being hit. This time with lower limit.
1000 RPCs waiting on "hbase:meta,,1" to come back online

**Comment by nragon** [comment]
It seems another table, other than the first I've mentioned is being hit, this time with lower limit.
1000 RPCs waiting on "hbase:meta,,1" to come back online

**Comment by jake-maloney** [comment]
The Meta table is being hit that much? Are you recreating your HbaseClient a lot? Once the client gets your Meta you shouldn't need to get it again unless the regions move around a lot. Is your HBase table pre-partitioned? It could be splitting regions excessively while you are loading tons of data which could cause all of the above problems.

**Comment by nragon** [comment]
I have 5 task managers in flink with 2 slots each. The client is created once per worker(5 totoal) with 
`this.client = new HBaseClient(config);` After that I only do `this.client.put(...)`
Regarding my table, it's not partitioned and maybe this issue is due to splitting. I've notice that one of my region servers is shutting down (during split?)

**Comment by nragon** [comment]
I believe each new key is queried on hbase:meta. My keys are composed of three dimensions, one of them being date.
RPC: HBaseRpc(method=getClosestRowBefore, table="hbase:meta", key="PGW_OUT_AGG,otf2016091917NA,:", region=RegionInfo(table="hbase:meta", region_name="hbase:meta,,1", stop_key=""), attempt=0, timeout=-1, hasTimedout=false)

**Comment by jake-maloney** [comment]
I am unfamiliar with the getClosestRowBefore RPC implementation but if it requires hitting meta for every request then that is problematic from a performance perspective.

**Comment by manolama** [comment]
So what's happening here is that yes, you're likely observing a backup on the AsyncHBase client due to the region server splitting. Until the NSRE is created and cached, the HBaseClient will hit Meta looking for the split region since the region server knows it's offline during the split. Generally this should only be in the order 10s of hits till each new Put is appended to the NSRE queue. Once the queue is full then you'll see this throttle limit till the region is back online.

Some things to try:
* Make sure you're using a newer AsyncHBase client. It has better probe support that should cut down on the hits to Meta.
* Pre-split your regions if you see this frequently. That will avoid the issue so you don't see the splits.
* When you do see this error you'll have to queue the value and retry storing it again after the region is back online.
* Try making your regions larger to avoid splits as well.
