### ISSUE TITLE
An exception was thrown by TimerTask. java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by wanygan83** [OpenTSDB/asynchbase#196]
2018-08-31 22:11:36,631 [AsyncHBase Timer HBaseClient #1] WARN  org.jboss.netty.util.HashedWheelTimer  - An exception was thrown by TimerTask.
java.lang.OutOfMemoryError: Java heap space
        at java.util.TimSort.sort(TimSort.java:230) ~[?:1.8.0_111]
        at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_111]
        at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_111]
        at java.util.Collections.sort(Collections.java:175) ~[?:1.8.0_111]
        at org.hbase.async.MultiAction.serialize(MultiAction.java:222) ~[asynchbase-1.8.2.jar!/:?]
        at org.hbase.async.RegionClient.encode(RegionClient.java:1294) ~[asynchbase-1.8.2.jar!/:?]
        at org.hbase.async.RegionClient.sendRpc(RegionClient.java:1005) ~[asynchbase-1.8.2.jar!/:?]
        at org.hbase.async.RegionClient.periodicFlush(RegionClient.java:351) ~[asynchbase-1.8.2.jar!/:?]
        at org.hbase.async.RegionClient.access$000(RegionClient.java:88) ~[asynchbase-1.8.2.jar!/:?]

**Comment by manolama** [comment]
Hi, this is often caused by the default NSRE queue size that can maintain thousands of RPCs for each region that is offline. Change `hbase.nsre.high_watermark` to something much smaller like `10`.
