### ISSUE TITLE
Why ConnectionResetException happen？

### ISSUE THREAD

**Issue by LostLegend** [OpenTSDB/asynchbase#211]
When i scan data from HBase, sometimes client will throws ConnectionResetException, looks like connection lost unexpected,but in region server, it has not any error or warn logs. thanks a lot if someone know about it.

org.hbase.async.ConnectionResetException: [id: 0x6c068e8a, /[my ip]:43398 :> /[my ip]:60020] got disconnected
        at org.hbase.async.RegionClient.cleanup(RegionClient.java:1179)
        at org.hbase.async.RegionClient.channelDisconnected(RegionClient.java:1158)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1230)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.channelDisconnected(SimpleChannelHandler.java:199)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:120)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)

my asynchbase version is 1.8.2, and HBase server version is 1.2.0

**Comment by bharathkuppala** [comment]
Hello, Were you able to find the solution or cause for this problem?
