### ISSUE TITLE
Can this support the kerberos authentication of hbase 2.2

### ISSUE THREAD

**Issue by AhDEV-free** [OpenTSDB/asynchbase#225]
Can this support the kerberos authentication of hbase 2.2;

i get a error.

eg：
Sasl initialization failed status = 1

**Comment by AhDEV-free** [comment]
I have already solved this problem,if you have a same question.

to [this error](https://github.com/OpenTSDB/opentsdb/issues/2162#issue-977660987)
```
2021-08-24 11:12:52,497 ERROR [AsyncHBase I/O Worker #1] RegionClient: Unexpected exception from downstream on [id: 0xdc48e63a, /10.4.132.9:51318 => /10.4.132.8:16020]
java.lang.SecurityException: Sasl initialization failed with a status of [1] and exception [javax.security.sasl.SaslException] and message [GSS initiate failed]: org.hbase.async.SecureRpcHelper96@51a1ef3c
        at org.hbase.async.SecureRpcHelper96.handleResponse(SecureRpcHelper96.java:133) ~[asynchbase-1.8.2.jar:na]
        at org.hbase.async.RegionClient.decode(RegionClient.java:1423) ~[asynchbase-1.8.2.jar:na]
```

 you should check your config:hbase.kerberos.regionserver.principal
my value is hbase/_HOST@ECLD.COM 

this value from hbase-site.xml 
```xml
    <property>
      <name>hbase.master.kerberos.principal</name>
      <value>hbase/_HOST@xxxxx.COM</value>
    </property>
```
